language: c

git:
  depth: 5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8-multilib
      - linux-libc-dev:i386

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libX11-dev:i386

compiler:
  - gcc-4.8

env:
  matrix:
    - CMAKE_C_FLAGS="-O3 -DNDEBUG -fPIC -msse2 -m32"
    - CMAKE_C_FLAGS="-O3 -DNDEBUG -fPIC"

before_script:
  - cd Modelica_DeviceDrivers/Resources

script:
  - cmake ./
  - make
  - cd test/Util
  - ./test_MDDMapIntInt
  - ./test_MDDMapIntpVoid
  - ./test_MDDUtilities
  - cd ../OperatingSystem
  - ./test_MDD_getTimeMS
  - sudo ./test_MDDRealtimeSynchronize_high
  - ./test_MDDRealtimeSynchronize_idle
  - ./test_MDDRealtimeSynchronize_low
  - ./test_MDDRealtimeSynchronize_normal
  - cd ../Communication
  - ./test_EndiannessConversion
  - ./test_MDDSerialPackager
  - ./test_MDDSharedMemory
  - ./test_MDDUDPSocket
  - cd ../..

notifications:
  email: false

# sudo: false
